//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleeteInvoicing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_CFDI_PRODUCTS
    {
        public string cfdiProductId { get; set; }
        public string cfdiProductDescription { get; set; }
        public Nullable<int> active { get; set; }
        public string user { get; set; }
    }
}
