//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleeteInvoicing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFD_HEADER
    {
        public string registryType { get; set; }
        public string CFDUniqueID { get; set; }
        public string headerSeries { get; set; }
        public string headerFolio { get; set; }
        public Nullable<System.DateTime> headerDate { get; set; }
        public Nullable<decimal> headerSubtotal { get; set; }
        public Nullable<decimal> headerTotal { get; set; }
        public Nullable<decimal> headerTaxes { get; set; }
        public Nullable<decimal> headerTaxes2 { get; set; }
        public Nullable<decimal> headerDiscount { get; set; }
        public string headerDiscountExplanation { get; set; }
        public string headerAmountLegend { get; set; }
        public string headerCurrency { get; set; }
        public Nullable<decimal> headerExchangeRate { get; set; }
        public string headerReference { get; set; }
        public string headerObs1 { get; set; }
        public string headerObs2 { get; set; }
        public string headerObs3 { get; set; }
        public string headerFleet { get; set; }
        public string headerDivision { get; set; }
        public string headerCreditDebitInd { get; set; }
        public string headerCorpCd { get; set; }
        public string headerInvTypeInd { get; set; }
        public string headerDocumentType { get; set; }
        public string headerPaymentMethodType { get; set; }
        public string headerZipCode { get; set; }
        public string headerConfirmation { get; set; }
        public string headerPaymentMethod { get; set; }
        public string headerPaymentConditions { get; set; }
        public string headerUUID { get; set; }
        public string headerParentSeries { get; set; }
        public string headerParentFolio { get; set; }
        public string headerPeriodicity { get; set; }
        public string headerTralixStatus { get; set; }
        public string headerInternalStatus { get; set; }
        public Nullable<System.DateTime> headerTralixStatusDate { get; set; }
        public string headerComments { get; set; }
    }
}
