//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleeteInvoicing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFD_EXPANDED_ADDRESS
    {
        public string CUSTID { get; set; }
        public string CORP_CD { get; set; }
        public string CNTC_NO { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string CUSTNAME { get; set; }
        public string RFC { get; set; }
        public string PAYMENT_METHOD_TYPE { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public string CREATEDBY { get; set; }
    }
}
