//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleeteInvoicing.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FleeteInvoicingEntities : DbContext
    {
        public FleeteInvoicingEntities()
            : base("name=FleeteInvoicingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAT_PAYMENTMETHODTYPE> CAT_PAYMENTMETHODTYPE { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<CAT_CFDI_PRODUCTS> CAT_CFDI_PRODUCTS { get; set; }
        public virtual DbSet<CAT_CURRENCY> CAT_CURRENCY { get; set; }
        public virtual DbSet<UNIVERSAL_COLLECTION> UNIVERSAL_COLLECTION { get; set; }
        public virtual DbSet<CFD_EXPANDED_ADDRESS> CFD_EXPANDED_ADDRESS { get; set; }
    }
}
