//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleeteInvoicing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIVERSAL_COLLECTION
    {
        public int id_universal { get; set; }
        public string uc_fleet { get; set; }
        public string uc_account { get; set; }
        public string uc_clabe { get; set; }
        public string uc_aba { get; set; }
        public string uc_swift { get; set; }
        public string uc_currency { get; set; }
    }
}
